name: DES Build Pipeline

on:
  push:
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Change to pipeline directory
      run: cd ../test
      working-directory: test/

    - name: Pipeline Compile Test
      run: make -f pipeline.make all
      working-directory: test/
    
    - name: Pipeline Run Test
      run: make -f pipeline.make test
      working-directory: test/
    
    - name: Pipeline Clean
      run: make -f pipeline.make clean
      working-directory: test/
