name: DES Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pipeline Compile Test
      run: make -f pipeline 
    - name: Pipeline Run Test
      run: make -f pipeline test
    - name: Pipeline Clean
      run: make -f pipeline clean
