name: DES Test Pipeline

on:
  push:
  pull_request:
    branches: [ "**" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile & Run Tests
      run: |
        cd ./test  
        make run   

    - name: Clean Up  
      run: |
        cd ./test  
        make clean 
